export type UiLocale = "en" | "sw";

export const uiCopy: Record<UiLocale, Record<string, string>> = {
  en: {
    home: "Home", discover: "Discover", shelf: "My shelf", signIn: "Sign in", language: "Language", english: "English", kiswahili: "Kiswahili",
    storiesForEveryday: "Stories for your everyday", findStory: "Find a story.", findMoment: "Find your moment.", heroLede: "Read fresh stories from Kenya in English and Kiswahili. Pick up where you left off, even when the signal drops.", startExploring: "Start exploring",
    searchPlaceholder: "Search title, author or keywords...", searchHotKey1: "Billionaire", searchHotKey2: "Romance", searchHotKey3: "Sun Queen",
    topRankings: "Top Rankings", editorChoice: "Editor's Choice", freeZone: "Free Novels", completedZone: "Completed Stories", bilingualZone: "Swahili / English",
    boysChannel: "Trending", girlsChannel: "Romance", heatPopularity: "{count}k Readers", scoreRating: "9.8 Top Rated", quickCategories: "Popular Categories", recommendForYou: "Recommended For You",
    handpicked: "Handpicked for you", featuredWeek: "Featured this week", seeAll: "See all", readNow: "Read now", popularNow: "Popular right now", keepTurning: "Keep turning pages", browseAll: "Browse all", readYourWay: "Read your way", storiesLanguages: "Stories in English & Kiswahili", justAdded: "Just added", newStories: "New stories", noStoriesLanguage: "Stories in this language are coming soon.", by: "By",
    closeStory: "A good story is close", allStories: "All stories", romance: "Romance", thriller: "Thriller", life: "Life", stories: "{count} stories", backDiscover: "Back to discover", freeToRead: "Free to read", startReading: "Start reading", addShelf: "Add to shelf", savedShelf: "On your shelf", chapters: "{count} chapters", updated: "Updated {time}", theStory: "The story", moreChapters: "More chapters coming soon", followStory: "Follow the story as new chapters are published.",
    back: "Back", previous: "Previous", nextChapter: "Next chapter", backBook: "Back to book", chapter: "Chapter {number}", offlineSaved: "This chapter is saved on your device for offline reading", readingSettings: "Reading settings", decreaseText: "Decrease text size", increaseText: "Increase text size", lineSpacing: "Line spacing", theme: "Theme", light: "Light", sepia: "Sepia", dark: "Dark", fullscreen: "Full screen", exitFullscreen: "Exit full screen", fullscreenUnavailable: "Full screen is not available in this browser.", download: "Download", downloadNext10: "Download next 10", downloadNext20: "Download next 20", downloaded: "Downloaded", downloading: "Downloading…",
    yourStories: "Your stories, your pace", offlineStories: "Offline stories", continueReading: "Continue reading", continue: "Continue", savedLater: "Saved for later", shelfGrowing: "Your shelf is growing", emptyShelf: "Your shelf is ready", emptyShelfText: "Save a story to continue reading it here.", exploreStories: "Explore stories",
    keepPlace: "Keep your place", welcomeBack: "Welcome back.", authCopy: "Sign in to sync your shelf and reading progress across devices.", google: "Continue with Google", orEmail: "or use your email", emailAddress: "Email address", sendCode: "Send me a code", guest: "You can also", keepGuest: "keep reading as a guest", checkEmail: "Check your email for a sign-in link.", authError: "We could not start sign-in. Please try again.",
    offlineTitle: "Offline stories", offlineText: "Downloaded chapters stay on this device and are ready when your connection drops.", noDownloads: "No downloads yet", noDownloadsText: "Open a story and download a chapter or the next 10 chapters for offline reading.", removeDownloads: "Remove downloads", downloadedChapters: "{count} downloaded chapters",
    studio: "Studio", overview: "Studio overview", newBook: "New book", readersToday: "Readers today", chaptersRead: "Chapters read", booksPublished: "Books published", returnRate: "Return rate", content: "Content", latestBooks: "Latest books", manageAll: "Manage all", readerJourney: "Reader journey", viewData: "View data", contentLibrary: "Content library", books: "Books", all: "All", published: "Published", drafts: "Drafts", searchBooks: "Search books", book: "Book", status: "Status", edit: "Edit", addBook: "Add a book", createBookText: "Create the book record first, then upload chapters from its edit page.", bookTitle: "Book title", authorName: "Author name", category: "Category", description: "Description", coverImage: "Cover image", saveDraft: "Save as draft", cancel: "Cancel", saveChanges: "Save changes", publish: "Publish", manageChapters: "Manage chapters", preview: "Preview", chapterManager: "Chapter manager", batchImport: "Batch import", batchImportText: "Upload TXT, Markdown or the standard JSON format.", chooseFile: "Choose file", addChapter: "Add chapter", batchBooksImport: "Import books in bulk", batchBooksImportText: "Upload one JSON file with up to 20 books and 1,000 chapters. Matching slugs update existing books and chapters.", chooseJsonFile: "Choose JSON file", importing: "Importing…", batchBooksImported: "Imported {books} books and {chapters} chapters.", batchBooksImportFailed: "Book import failed.", batchBooksInvalidFile: "Choose a valid JSON file with a books array.", analytics: "Analytics", readerSignals: "Reader signals", last7Days: "Last 7 days", bookViews: "Book detail views", chapter1Completion: "Chapter 1 completion", chapter3Reach: "Chapter 3 reach", offlineDownloads: "Offline downloads", coreFunnel: "Core funnel", clickToReturn: "From click to return", bookDetail: "Book detail", chapter1Start: "Chapter 1 start", chapter3Finish: "Chapter 3 finish", nextDayReturn: "Next-day return",
    clearAllBooks: "Delete all books", clearingBooks: "Deleting…", clearBooksConfirm: "Delete all {count} books, their chapters, reading progress, and uploaded covers? This cannot be undone.", booksCleared: "Deleted {count} books.",
  },
  sw: {
    home: "Nyumbani", discover: "Gundua", shelf: "Rafu yangu", signIn: "Ingia", language: "Lugha", english: "Kiingereza", kiswahili: "Kiswahili",
    storiesForEveryday: "Hadithi za kila siku", findStory: "Pata hadithi.", findMoment: "Pata muda wako.", heroLede: "Soma hadithi mpya kutoka Kenya kwa Kiingereza na Kiswahili. Endelea ulipoishia, hata mtandao unapokatika.", startExploring: "Anza kugundua",
    searchPlaceholder: "Tafuta jina la kitabu, mwandishi...", searchHotKey1: "Mabilionea", searchHotKey2: "Mapenzi", searchHotKey3: "Malkia wa Jua",
    topRankings: "Orodha ya Juu", editorChoice: "Zilizochaguliwa", freeZone: "Hadithi za Bure", completedZone: "Zilizokamilika", bilingualZone: "Lugha Mbili",
    boysChannel: "Zinazovuma", girlsChannel: "Mapenzi", heatPopularity: "Wasomaji {count}k", scoreRating: "Alama 9.8", quickCategories: "Aina Maarufu", recommendForYou: "Imependekezwa Kwako",
    handpicked: "Zilizochaguliwa kwa ajili yako", featuredWeek: "Maarufu wiki hii", seeAll: "Tazama zote", readNow: "Soma sasa", popularNow: "Maarufu sasa", keepTurning: "Endelea kugeuza kurasa", browseAll: "Vinjari zote", readYourWay: "Soma kwa njia yako", storiesLanguages: "Hadithi kwa Kiingereza na Kiswahili", justAdded: "Zilizoongezwa", newStories: "Hadithi mpya", noStoriesLanguage: "Hadithi katika lugha hii zinakuja hivi karibuni.", by: "Na",
    closeStory: "Hadithi nzuri iko karibu", allStories: "Hadithi zote", romance: "Mapenzi", thriller: "Kusisimua", life: "Maisha", stories: "Hadithi {count}", backDiscover: "Rudi kwenye ugunduzi", freeToRead: "Soma bure", startReading: "Anza kusoma", addShelf: "Ongeza kwenye rafu", savedShelf: "Ipo kwenye rafu", chapters: "Sura {count}", updated: "Imeongezwa {time}", theStory: "Hadithi", moreChapters: "Sura zaidi zinakuja", followStory: "Fuata hadithi sura mpya zinapochapishwa.",
    back: "Rudi", previous: "Iliyotangulia", nextChapter: "Sura inayofuata", backBook: "Rudi kwenye kitabu", chapter: "Sura ya {number}", offlineSaved: "Sura hii imehifadhiwa kwenye kifaa chako kwa kusoma bila mtandao", readingSettings: "Mipangilio ya kusoma", decreaseText: "Punguza ukubwa wa maandishi", increaseText: "Ongeza ukubwa wa maandishi", lineSpacing: "Nafasi za mistari", theme: "Mandhari", light: "Nyeupe", sepia: "Krimu", dark: "Giza", fullscreen: "Skrini nzima", exitFullscreen: "Ondoka skrini nzima", fullscreenUnavailable: "Skrini nzima haipatikani kwenye kivinjari hiki.", download: "Pakua", downloadNext10: "Pakua 10 zijazo", downloadNext20: "Pakua 20 zijazo", downloaded: "Imepakuliwa", downloading: "Inapakua…",
    yourStories: "Hadithi zako, kwa mwendo wako", offlineStories: "Hadithi bila mtandao", continueReading: "Endelea kusoma", continue: "Endelea", savedLater: "Zilizohifadhiwa", shelfGrowing: "Rafu yako inakua", emptyShelf: "Rafu yako iko tayari", emptyShelfText: "Hifadhi hadithi ili uendelee kuisoma hapa.", exploreStories: "Gundua hadithi",
    keepPlace: "Hifadhi ulipo", welcomeBack: "Karibu tena.", authCopy: "Ingia ili rafu na maendeleo yako ya kusoma yaunganishwe kwenye vifaa vyako.", google: "Endelea na Google", orEmail: "au tumia barua pepe", emailAddress: "Barua pepe", sendCode: "Nitumie kiungo", guest: "Unaweza pia", keepGuest: "kuendelea kama mgeni", checkEmail: "Angalia barua pepe yako kwa kiungo cha kuingia.", authError: "Hatukuweza kuanzisha kuingia. Tafadhali jaribu tena.",
    offlineTitle: "Hadithi bila mtandao", offlineText: "Sura zilizopakuliwa hubaki kwenye kifaa hiki na ziko tayari mtandao unapokatika.", noDownloads: "Hakuna vilivyopakuliwa bado", noDownloadsText: "Fungua hadithi na upakue sura au sura 10 zinazofuata ili usome bila mtandao.", removeDownloads: "Ondoa vilivyopakuliwa", downloadedChapters: "Sura {count} zimepakuliwa",
    studio: "Studio", overview: "Muhtasari wa Studio", newBook: "Kitabu kipya", readersToday: "Wasomaji leo", chaptersRead: "Sura zilizosomwa", booksPublished: "Vitabu vilivyochapishwa", returnRate: "Kiwango cha kurudi", content: "Maudhui", latestBooks: "Vitabu vya karibuni", manageAll: "Dhibiti vyote", readerJourney: "Safari ya msomaji", viewData: "Tazama data", contentLibrary: "Maktaba ya maudhui", books: "Vitabu", all: "Vyote", published: "Vimechapishwa", drafts: "Rasimu", searchBooks: "Tafuta vitabu", book: "Kitabu", status: "Hali", edit: "Hariri", addBook: "Ongeza kitabu", createBookText: "Anzisha rekodi ya kitabu, kisha pakia sura kwenye ukurasa wa uhariri.", bookTitle: "Jina la kitabu", authorName: "Jina la mwandishi", category: "Aina", description: "Maelezo", coverImage: "Picha ya jalada", saveDraft: "Hifadhi rasimu", cancel: "Ghairi", saveChanges: "Hifadhi mabadiliko", publish: "Chapisha", manageChapters: "Dhibiti sura", preview: "Hakiki", chapterManager: "Msimamizi wa sura", batchImport: "Pakia kwa pamoja", batchImportText: "Pakia TXT, Markdown au muundo wa kawaida wa JSON.", chooseFile: "Chagua faili", addChapter: "Ongeza sura", batchBooksImport: "Pakia vitabu vingi", batchBooksImportText: "Pakia faili moja ya JSON yenye hadi vitabu 20 na sura 1,000. Slug zinazolingana husasisha vitabu na sura zilizopo.", chooseJsonFile: "Chagua faili ya JSON", importing: "Inapakia…", batchBooksImported: "Vitabu {books} na sura {chapters} zimepakiwa.", batchBooksImportFailed: "Upakiaji wa vitabu umeshindikana.", batchBooksInvalidFile: "Chagua faili sahihi ya JSON yenye orodha ya books.", analytics: "Uchanganuzi", readerSignals: "Ishara za wasomaji", last7Days: "Siku 7 zilizopita", bookViews: "Kutazama kitabu", chapter1Completion: "Kumaliza sura ya 1", chapter3Reach: "Kufikia sura ya 3", offlineDownloads: "Vipakuliwa bila mtandao", coreFunnel: "Mtiririko mkuu", clickToReturn: "Kutoka kubofya hadi kurudi", bookDetail: "Maelezo ya kitabu", chapter1Start: "Kuanza sura ya 1", chapter3Finish: "Kumaliza sura ya 3", nextDayReturn: "Kurudi siku inayofuata",
    clearAllBooks: "Futa vitabu vyote", clearingBooks: "Inafuta…", clearBooksConfirm: "Futa vitabu {count}, sura zake, maendeleo ya kusoma na jalada zilizopakiwa? Huwezi kutengua.", booksCleared: "Vitabu {count} vimefutwa.",
  },
};
